[build]
  base = "frontend/"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "https://taskmanager2-l4in.onrender.com/api/:splat"
  status = 200
  force = true

[build.environment]
  REACT_APP_API_URL = "https://taskmanager2-l4in.onrender.com/api"
  NODE_VERSION = "18"
